### ISSUE TITLE
Action.WhenJailed: Get actor name

### ISSUE THREAD

**Issue by f9a** [jaredfolkins/badactor#6]
Hello Jared,

very nice library, thanks for your effort!

I would like to use Action.WhenJailed to report violations via email. For this I would need the name of the blocked actor. Is there a way to read this from *Actor? It would be very convenient. 

Thank you very much and best regards!

**Comment by jaredfolkins** [comment]
Solved with this commit. 

https://github.com/jaredfolkins/badactor/commit/1d1f4105ddd60d654b006be03839da20c7933e6d
